apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    namespace: default
    annotations:
        tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:jbofFr3LsY2Fu0UB,iv:jqsb4EPbsNDjq04cI8L/7q4o8nHwkDLcDJav/VKX6xw=,tag:7PrJd0wrfjO6shzPshfL6Q==,type:str]
    password: ENC[AES256_GCM,data:wJnNUFgos9xOnzK4gNuJQfx8MusyT9wnHE1VG2uUOTwLQabz/OjIaf52KX+mMtfjXDOB+k7m2hk=,iv:7qgb4i26VVlNBHoIdNwMpGchFIMsmhplehCOenQUPS4=,tag:qb5GHnYU/y8kwuKbqJsIuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdlQ3UUJNdjJPdnp5QnFD
            NVB2RENsbytDeG1aVFNnSWpFRXIvN1k1TGgwCjl2OFU4dVQ1Q2doWkJVT0VETS9y
            a3lXSTJ3MnBVVnB3UkVBUUYweE03MEkKLS0tIGlLTGZxcmJoS0J1WWF6MHYzMEhL
            K2lOR3RHWDhRa0pxcGdxZGhEcWFydlUKUZIccfNOVjrOOuMqWo/UvKq3iYvAQUJO
            bsQFLs+VIBwInEl/h78uqGH46+c1t8jcPTcE2lqVkVeee+hX6Hv0IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15km9ru9zvtecpljnjfsx7chq6fpj0jlsumyhacj097v2gxhtx3ls7upjha
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T12:20:25Z"
    mac: ENC[AES256_GCM,data:nwLnTl8lSGShggr/xN5yi5gVwMFrzyxuHXEwKD52KaGqIvQp27s4EYLmPmMT13uax6FMOCLcDmbwat8jmJDEXhLPxpPmAUr3yfKHvSPZAh8RY09xmwG+Hjjjwi+rhqFqBY/7utVP4nT41vNFgGk0PWxku4jhka2TihvKGk9eENI=,iv:XBF8JV8mqhZijRHXv8y6z0CPg7tgtaQvWaHRHJsdzpA=,tag:Fyeq4rDB1v1fVrvHqyt+Sw==,type:str]
    version: 3.13.3
