apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: infrastructure
  path: ./clusters/kind/apps
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
