apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-pipeline
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: tekton
  path: ./clusters/kind/tekton-pipeline
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
